/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreadCrumbs: typeof import('./src/layout/components/BreadCrumbs.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    FormDrawer: typeof import('./src/components/FormDrawer.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpArraodown: typeof import('~icons/ep/arraodown')['default']
    IEpArraoDown: typeof import('~icons/ep/arrao-down')['default']
    IEpArraown: typeof import('~icons/ep/arraown')['default']
    IEpArrowdown: typeof import('~icons/ep/arrowdown')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpArrowown: typeof import('~icons/ep/arrowown')['default']
    IEpArrowOwn: typeof import('~icons/ep/arrow-own')['default']
    IEpElementPlus: typeof import('~icons/ep/element-plus')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpPrinter: typeof import('~icons/ep/printer')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/layout/components/SideMenu.vue')['default']
    TopNav: typeof import('./src/layout/components/TopNav.vue')['default']
  }
}
